/*  Проверка и апдейт прав (установка однотипных прав всем пользователям по ролям   */
select 
	p.LastName,
	u.RolesGuid, 
	u.Rights
FROM users as [u]
INNER JOIN Persons as [p] ON u.PersonsGuid = p.Guid

where IsActive = 1
and RolesGuid IN ('00000000-0000-0000-0000-000000000001', '00000000-0000-0000-0000-000000000002', '00000000-0000-0000-0000-000000000004')
ORDER BY RolesGuid

/*
-- Аналитики
UPDATE [users] 
	SET [Rights] = 'ANALYST_ID,CONNECT_AS_CLIENT,ALL_DRV_STATES,SEMI_DRV_STATES,VIEW_ALARM,VIEW_ALARM_JOURNAL_SLEEP,VIEW_ALARM_JOURNAL_STRESS,VIEW_ALARM_JOURNAL_MILLIAGE,VIEW_ALARM_JOURNAL_ROUTES,VIEW_ALARM_JOURNAL_DEVICES,VIEW_ALARM_JOURNAL_SENSORS,VIEW_ALARM_JOURNAL_SERVERS,VIEW_ALARM_JOURNAL_TRAIN,VIEW_ALARM_JOURNAL_RRERROR,VIEW_ALARM_JOURNAL_NODRIVER,'
	WHERE [RolesGuid] = '00000000-0000-0000-0000-000000000004'

--*/

/*
-- Операторы 
UPDATE [users] 
	SET [Rights] = 'CONNECT_AS_CLIENT,EDIT_ROUTES,CONFIRM_ALARM,VIEW_STATE,VIEW_HISTORY_STATE,ALL_DRV_STATES,SEMI_DRV_STATES,VIEW_ALARM,VIEW_ALARM_JOURNAL_SLEEP,VIEW_ALARM_JOURNAL_STRESS,VIEW_ALARM_JOURNAL_MILLIAGE,VIEW_ALARM_JOURNAL_SENDTOMEDINS,VIEW_ALARM_JOURNAL_ROUTES,VIEW_ALARM_JOURNAL_DEVICES,VIEW_ALARM_JOURNAL_SENSORS,VIEW_ALARM_JOURNAL_SERVERS,VIEW_ALARM_JOURNAL_TRAIN,VIEW_ALARM_JOURNAL_RRERROR,VIEW_ALARM_JOURNAL_NODRIVER,'
	WHERE [RolesGuid] = '00000000-0000-0000-0000-000000000002'

--*/


/*
-- Администраторы
UPDATE [users] 
	SET [Rights] = 'SUPERVISOR,ANALYST_ID,CONNECT_AS_GARNITURE,CONNECT_AS_CLIENT,EDIT_OPTIONS,EDIT_DICTIONARIES,EDIT_ROUTES,CONFIRM_ALARM,VIEW_STATE,VIEW_HISTORY_STATE,ALL_DRV_STATES,SEMI_DRV_STATES,UNDEFINED_DRV_STATE,VIEW_DRIVERS_DIGNALS,JOURNAL_ALL_EVENTS,JOURNAL_USERS,JOURNAL_BLOCKS,JOURNAL_SENSORS,JOURNAL_SERVER,JOURNAL_TRAIN,JOURNAL_ROUTES,JOURNAL_DEVICES,VIEW_ALARM,VIEW_ALARM_JOURNAL_SLEEP,VIEW_ALARM_JOURNAL_STRESS,VIEW_ALARM_JOURNAL_MILLIAGE,VIEW_ALARM_JOURNAL_SENDTOMEDINS,VIEW_ALARM_JOURNAL_MEDNOTPASS,VIEW_ALARM_JOURNAL_ROUTES,VIEW_ALARM_JOURNAL_DEVICES,VIEW_ALARM_JOURNAL_SENSORS,VIEW_ALARM_JOURNAL_SERVERS,VIEW_ALARM_JOURNAL_TRAIN,VIEW_ALARM_JOURNAL_RRERROR,VIEW_ALARM_JOURNAL_NODRIVER,'
	WHERE [RolesGuid] = '00000000-0000-0000-0000-000000000001'


--*/